version: '3.3'
services:
  mysql:
    container_name: simple_api
    image: mysql:5.6
    ports:
      - '3306:3306'
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: temp
      MYSQL_DATABASE: simple_api
