Resources:
  RDSSecurityGroup:
    DependsOn: VPC
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Ingress for RDS Instance
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId:
          Ref: LambdaSecurityGroup
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId:
          Ref: PublicInstanceSG
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "RDS Subnet Group"
      SubnetIds:
      - Ref: PrivateSubnetA
      - Ref: PrivateSubnetB
  RDSCluster:
    DependsOn: RDSSecurityGroup
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Retain
    Properties:
      Engine: aurora
      DatabaseName: simple_api_${self:provider.stage}
      MasterUsername: ${self:provider.environment.RDS_USER}
      MasterUserPassword: ${self:provider.environment.RDS_PWD}
      DBClusterParameterGroupName: default.aurora5.6
      EngineVersion: 5.6.10a
      EngineMode: serverless
      BackupRetentionPeriod: 7
      DeletionProtection : true
      ScalingConfiguration:
        AutoPause: false
        MinCapacity: 2
        MaxCapacity: 64
      StorageEncrypted: true
      VpcSecurityGroupIds:
        - Ref: RDSSecurityGroup
      DBSubnetGroupName:
        Ref: RDSSubnetGroup
